/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makeapp;

/**
 *
 * @author DELL
 */
public class Pass extends javax.swing.JPanel {

    /**
     * Creates new form Pass
     */
    
    public Pass() {
        initComponents();
        x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n1 = new javax.swing.JLayeredPane();
        x1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLayeredPane();
        x2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLayeredPane();
        x3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLayeredPane();
        x4 = new javax.swing.JLabel();
        n5 = new javax.swing.JLayeredPane();
        x5 = new javax.swing.JLabel();
        n6 = new javax.swing.JLayeredPane();
        x6 = new javax.swing.JLabel();
        n7 = new javax.swing.JLayeredPane();
        x7 = new javax.swing.JLabel();
        n8 = new javax.swing.JLayeredPane();
        x8 = new javax.swing.JLabel();
        n9 = new javax.swing.JLayeredPane();
        x9 = new javax.swing.JLabel();
        n0 = new javax.swing.JLayeredPane();
        x10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n1.setLayer(x1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n1Layout = new javax.swing.GroupLayout(n1);
        n1.setLayout(n1Layout);
        n1Layout.setHorizontalGroup(
            n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n1Layout.setVerticalGroup(
            n1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(n1Layout.createSequentialGroup()
                .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 80, 70));

        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
        });

        x2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n2.setLayer(x2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n2Layout = new javax.swing.GroupLayout(n2);
        n2.setLayout(n2Layout);
        n2Layout.setHorizontalGroup(
            n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n2Layout.setVerticalGroup(
            n2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 70, 80));

        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
        });

        x3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n3.setLayer(x3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n3Layout = new javax.swing.GroupLayout(n3);
        n3.setLayout(n3Layout);
        n3Layout.setHorizontalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n3Layout.setVerticalGroup(
            n3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 80, 80));

        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
        });

        x4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n4.setLayer(x4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n4Layout = new javax.swing.GroupLayout(n4);
        n4.setLayout(n4Layout);
        n4Layout.setHorizontalGroup(
            n4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n4Layout.setVerticalGroup(
            n4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 70));

        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
        });

        x5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n5.setLayer(x5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n5Layout = new javax.swing.GroupLayout(n5);
        n5.setLayout(n5Layout);
        n5Layout.setHorizontalGroup(
            n5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n5Layout.setVerticalGroup(
            n5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 70, 80));

        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
        });

        x6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n6.setLayer(x6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n6Layout = new javax.swing.GroupLayout(n6);
        n6.setLayout(n6Layout);
        n6Layout.setHorizontalGroup(
            n6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
        );
        n6Layout.setVerticalGroup(
            n6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n6Layout.createSequentialGroup()
                .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 80, 80));

        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
        });

        x7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N

        n7.setLayer(x7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout n7Layout = new javax.swing.GroupLayout(n7);
        n7.setLayout(n7Layout);
        n7Layout.setHorizontalGroup(
            n7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        n7Layout.setVerticalGroup(
            n7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 80, 80));

        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
        });
        n8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N
        n8.add(x8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 90, 95));

        add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 70, 70));

        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
        });
        n9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N
        n9.add(x9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 80, 80));

        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n0MouseClicked(evt);
            }
        });
        n0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Backgrsgin.jpg"))); // NOI18N
        n0.add(x10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 90, 80));

        add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pass.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 560));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+1;
        x1.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
                
            }
        
        
    }//GEN-LAST:event_n1MouseClicked

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+2;
        x2.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905){
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n2MouseClicked

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+3;
        x3.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n3MouseClicked

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+4;x4.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
       
    }//GEN-LAST:event_n4MouseClicked

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+5;x5.setVisible(true);
        Menu.dma++; 
        if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
       
    }//GEN-LAST:event_n5MouseClicked

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+6;x6.setVisible(true);
        Menu.dma++;
        if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n6MouseClicked

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+7;x7.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n7MouseClicked

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+8;x8.setVisible(true);
        Menu.dma++;
        if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n8MouseClicked

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10+9;x9.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n9MouseClicked

    private void n0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseClicked
        // TODO add your handling code here:
        Menu.ma=Menu.ma*10;x10.setVisible(true);
        Menu.dma++;if (Menu.dma==4) {
                if (Menu.ma==2905) {
                    Menu.pass.setVisible(false);
                    Menu.sgin1.setVisible(true);
                }
                else Menu.ma=0;
                Menu.dma=0;x1.setVisible(false);
        x2.setVisible(false);
        x3.setVisible(false);
        x4.setVisible(false);
        x5.setVisible(false);
        x6.setVisible(false);
        x7.setVisible(false);
        x8.setVisible(false);
        x9.setVisible(false);
        x10.setVisible(false);
            }
        
    }//GEN-LAST:event_n0MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane n0;
    private javax.swing.JLayeredPane n1;
    private javax.swing.JLayeredPane n2;
    private javax.swing.JLayeredPane n3;
    private javax.swing.JLayeredPane n4;
    private javax.swing.JLayeredPane n5;
    private javax.swing.JLayeredPane n6;
    private javax.swing.JLayeredPane n7;
    private javax.swing.JLayeredPane n8;
    private javax.swing.JLayeredPane n9;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x10;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    private javax.swing.JLabel x4;
    private javax.swing.JLabel x5;
    private javax.swing.JLabel x6;
    private javax.swing.JLabel x7;
    private javax.swing.JLabel x8;
    private javax.swing.JLabel x9;
    // End of variables declaration//GEN-END:variables
}
