/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makeapp;

import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import static makeapp.Menu.show1;

/**
 *
 * @author DELL
 */
public class Show11 extends javax.swing.JPanel {

    public DefaultTableModel model;
    long tr,tv,cl,dkc;
    public Show11() {
        dkc=1;tr=0;tv=0;cl=0;
        initComponents();
        
    }
        public void docdata(){
        ArrayList <Data> lis = new ArrayList<>();
        try (Scanner sc = new Scanner(new File("Data1.txt"))) {
           
                while (sc.hasNext()){
                    Data s = new Data();
                    s.setDay1(sc.nextLine());
                    s.setName(sc.nextLine());
                    s.setMoney(Long.parseLong(sc.nextLine()));
                    s.setNote(sc.nextLine());
                }
            
        } catch (Exception e) {
        }
        Menu.list= lis;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableshow = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        tvtext = new javax.swing.JLabel();
        trtext = new javax.swing.JLabel();
        cltext = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Người Thêm", "Số Tiền", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableshow.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableshowAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tableshowAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(tableshow);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 560, 251));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Còn Lại :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tổng Ra :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tổng Vào :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, 40));

        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-arrow (1).png"))); // NOI18N

        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        tvtext.setForeground(new java.awt.Color(0, 255, 0));
        tvtext.setText("jLabel5");
        tvtext.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tvtextAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(tvtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, 40));

        trtext.setForeground(new java.awt.Color(255, 0, 0));
        trtext.setText("jLabdel5");
        trtext.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                trtextAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(trtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 290, 100, 40));

        cltext.setForeground(new java.awt.Color(0, 204, 0));
        cltext.setText("jLabel5");
        cltext.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cltextAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(cltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
        // TODO add your handling code here:
        Menu.show1.setVisible(false);Menu.dkdemo=0;
       // model.removeTableModelListener(tableshow);
    }//GEN-LAST:event_jLayeredPane1MouseClicked

    private void tableshowAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableshowAncestorAdded
        // TODO add your handling code here:
        if (dkc!=0){
        this.model = (DefaultTableModel) tableshow.getModel();
        for (Data s: Menu.list){
        long tam=s.getMoney();
        if (tam>0) tv=tv+tam;
        else tr=tr+tam;cl=cl+tam;
        model.addRow(new Object[]{
            s.getDay1(),s.getName(),s.getMoney(),s.getNote()
        });
        }
        dkc=0;
        }
    }//GEN-LAST:event_tableshowAncestorAdded

    private void tableshowAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableshowAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableshowAncestorRemoved

    private void tvtextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tvtextAncestorAdded
        // TODO add your handling code here:
        tvtext.setText(tv+" VNĐ ");
    }//GEN-LAST:event_tvtextAncestorAdded

    private void trtextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_trtextAncestorAdded
        // TODO add your handling code here:
        trtext.setText((0-tr)+" VNĐ ");
    }//GEN-LAST:event_trtextAncestorAdded

    private void cltextAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cltextAncestorAdded
        // TODO add your handling code here:
        cltext.setText(cl+" VNĐ ");
        if (cl<0) cltext.setForeground(Color.red);
        else cltext.setForeground(Color.GREEN);
    }//GEN-LAST:event_cltextAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cltext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableshow;
    private javax.swing.JLabel trtext;
    private javax.swing.JLabel tvtext;
    // End of variables declaration//GEN-END:variables
}
