/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makeapp;

import java.awt.Component;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Tieu extends javax.swing.JPanel {

    private Component rootPane;

    /**
     * Creates new form Tieu
     */
    public Tieu() {
        initComponents();
        cDay2.setVisible(false);
        cMoney2.setVisible(false);
        cName2.setVisible(false);
        cNote2.setVisible(false);
        
    }
     private int ktranhapname(){
        if (nhapname2.getText().length()<1) return 0;
        return 1;
    }  
    private int ktranhapmoney(){
        long d=0;
        if (nhapmoney2.getText().length()<1) return 0;
        d=Long.parseLong(nhapmoney2.getText());
        if ((d!=0)&&d<500) return 0;
        if (d<500) return 0;
        return 1;
    }  
     private int ktranhapnote(){
        if (nhapnote2.getText().length()<1) return 0;
        return 1;
    }  
    
    private int ktranhapday(){
        if (nhapday2.getText().length()<10) return 0;
        if ((nhapday2.getText().charAt(2)!='/')||(nhapday2.getText().charAt(5)!='/')) return 0;
        return 1;
    }  
    public void ghidata(){
        try (PrintWriter pw = new PrintWriter(new File("Data1.txt"))) {
            for (Data s: Menu.list){
                pw.println(s.getDay1());
                   pw.println(s.getName());
                   pw.println(s.getMoney());
                   pw.println(s.getNote());
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cDay = new javax.swing.JLabel();
        nhapday1 = new javax.swing.JTextField();
        cName = new javax.swing.JLabel();
        nhapname1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cMoney = new javax.swing.JLabel();
        nhapmoney1 = new javax.swing.JTextField();
        cNote = new javax.swing.JLabel();
        nhapnote1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nhapday2 = new javax.swing.JTextField();
        nhapname2 = new javax.swing.JTextField();
        nhapmoney2 = new javax.swing.JTextField();
        nhapnote2 = new javax.swing.JTextField();
        cDay2 = new javax.swing.JLabel();
        cName2 = new javax.swing.JLabel();
        cMoney2 = new javax.swing.JLabel();
        cNote2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        cDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N

        cName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ngày :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Người Thêm :");

        cMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N

        cNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ghi Chú : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Số Tiền : ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/piggy-bank (1).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N

        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 260));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ngày :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Người Thêm :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 31));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Số Tiền : ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ghi Chú : ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        add(nhapday2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 234, -1));
        add(nhapname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 234, -1));
        add(nhapmoney2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 234, -1));
        add(nhapnote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 234, -1));

        cDay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        add(cDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 40));

        cName2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        add(cName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 40));

        cMoney2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        add(cMoney2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 40));

        cNote2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checked.png"))); // NOI18N
        add(cNote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 156, -1, 50));

        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 50, 50));

        jLayeredPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane2MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/money.png"))); // NOI18N

        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back-arrow (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
        // TODO add your handling code here:
        Menu.tieu1.setVisible(false);Menu.dkdemo=0;
        nhapday2.setText("");
        nhapname2.setText("");
        nhapmoney2.setText("");
        nhapnote2.setText("");
        cDay2.setVisible(false);
        cMoney2.setVisible(false);
        cName2.setVisible(false);
        cNote2.setVisible(false);
    }//GEN-LAST:event_jLayeredPane1MouseClicked

    private void jLayeredPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane2MouseClicked
        // TODO add your handling code here:
        int c1=ktranhapday();
        int c2=ktranhapname();
        int c3=ktranhapmoney();
        int c4=ktranhapnote();
        if (c1+c2+c3+c4<4){
            JOptionPane.showMessageDialog(rootPane,"Thông Tin Không Hợp Lệ");
            if (c1==1) cDay2.setVisible(true);
            else cDay.setVisible(false);
            if (c2==1) cName2.setVisible(true);
            else cName.setVisible(false);
            if (c3==1) cMoney2.setVisible(true);
            else cMoney.setVisible(false);
            if (c4==1) cNote2.setVisible(true);
            else cNote.setVisible(false);
        }
        else
        {
        cDay2.setVisible(true);
        cMoney2.setVisible(true);
        cName2.setVisible(true);
        cNote2.setVisible(true);
        JOptionPane.showMessageDialog(rootPane,"Đã Lưu Thông Tin");
        Data s = new Data();
        s.setDay1(nhapday2.getText());
        s.setName(nhapname2.getText());
        s.setMoney(0-Long.parseLong(nhapmoney2.getText()));
        s.setNote(nhapnote2.getText());
        if (Menu.show1.tv!=0){Menu.show1.tr+=s.getMoney();
        Menu.show1.cl+=s.getMoney();
        }
        Menu.list.add(s);
        ghidata();
        Menu.show1.model.addRow(new Object[]{
            s.getDay1(),s.getName(),s.getMoney(),s.getNote()
        });
        }
    }//GEN-LAST:event_jLayeredPane2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cDay;
    private javax.swing.JLabel cDay2;
    private javax.swing.JLabel cMoney;
    private javax.swing.JLabel cMoney2;
    private javax.swing.JLabel cName;
    private javax.swing.JLabel cName2;
    private javax.swing.JLabel cNote;
    private javax.swing.JLabel cNote2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField nhapday1;
    private javax.swing.JTextField nhapday2;
    private javax.swing.JTextField nhapmoney1;
    private javax.swing.JTextField nhapmoney2;
    private javax.swing.JTextField nhapname1;
    private javax.swing.JTextField nhapname2;
    private javax.swing.JTextField nhapnote1;
    private javax.swing.JTextField nhapnote2;
    // End of variables declaration//GEN-END:variables
}
